/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.1.6 (4.1)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiv4_1

import (
	"encoding/json"
)

// checks if the ModuleTypeAirflow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModuleTypeAirflow{}

// ModuleTypeAirflow struct for ModuleTypeAirflow
type ModuleTypeAirflow struct {
	// * `front-to-rear` - Front to rear * `rear-to-front` - Rear to front * `left-to-right` - Left to right * `right-to-left` - Right to left * `side-to-rear` - Side to rear * `passive` - Passive
	Value                NullableString `json:"value,omitempty"`
	Label                *string        `json:"label,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ModuleTypeAirflow ModuleTypeAirflow

// NewModuleTypeAirflow instantiates a new ModuleTypeAirflow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModuleTypeAirflow() *ModuleTypeAirflow {
	this := ModuleTypeAirflow{}
	return &this
}

// NewModuleTypeAirflowWithDefaults instantiates a new ModuleTypeAirflow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModuleTypeAirflowWithDefaults() *ModuleTypeAirflow {
	this := ModuleTypeAirflow{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModuleTypeAirflow) GetValue() string {
	if o == nil || IsNil(o.Value.Get()) {
		var ret string
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModuleTypeAirflow) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *ModuleTypeAirflow) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableString and assigns it to the Value field.
func (o *ModuleTypeAirflow) SetValue(v string) {
	o.Value.Set(&v)
}

// SetValueNil sets the value for Value to be an explicit nil
func (o *ModuleTypeAirflow) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *ModuleTypeAirflow) UnsetValue() {
	o.Value.Unset()
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *ModuleTypeAirflow) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModuleTypeAirflow) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *ModuleTypeAirflow) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *ModuleTypeAirflow) SetLabel(v string) {
	o.Label = &v
}

func (o ModuleTypeAirflow) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModuleTypeAirflow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ModuleTypeAirflow) UnmarshalJSON(data []byte) (err error) {
	varModuleTypeAirflow := _ModuleTypeAirflow{}

	err = json.Unmarshal(data, &varModuleTypeAirflow)

	if err != nil {
		return err
	}

	*o = ModuleTypeAirflow(varModuleTypeAirflow)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		delete(additionalProperties, "label")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableModuleTypeAirflow struct {
	value *ModuleTypeAirflow
	isSet bool
}

func (v NullableModuleTypeAirflow) Get() *ModuleTypeAirflow {
	return v.value
}

func (v *NullableModuleTypeAirflow) Set(val *ModuleTypeAirflow) {
	v.value = val
	v.isSet = true
}

func (v NullableModuleTypeAirflow) IsSet() bool {
	return v.isSet
}

func (v *NullableModuleTypeAirflow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModuleTypeAirflow(val *ModuleTypeAirflow) *NullableModuleTypeAirflow {
	return &NullableModuleTypeAirflow{value: val, isSet: true}
}

func (v NullableModuleTypeAirflow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModuleTypeAirflow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
